### ISSUE TITLE
My own Win-64 build version get worse compression ratio than lizard-1.0-windows

### ISSUE THREAD

**Issue by yunhua-deng** [inikep/lz5#17]
Compiler: Visual Studio 2017 64-Bit Community Edition
OS: Windows 10 64-bit
Binary size: my version **lizard-MyBuild.exe** (200+ KB) v.s. official version **lizard.exe** (500+KB)
File to compress: some Android firmware image (namely, "system-other.img")

As you can see from the results attached below, compression ratio of **lizard-MyBuild.exe** is always not as good as the **lizard.exe** given the same level (e.g., 25, 29, 45, 49). **Any idea on this difference?**

Compression ratio of **lizard-MyBuild.exe**:
- .\lizard-MyBuild.exe -25f .\system_other.img .\system_other.img.liz.25 (Compressed 371409248 bytes into 187947816 bytes ==> 50.60%)  
- .\lizard-MyBuild.exe -29f .\system_other.img .\system_other.img.liz.29 (Compressed 371409248 bytes into 186106560 bytes ==> 50.11%)
- .\lizard-MyBuild.exe -45f .\system_other.img .\system_other.img.liz.45 (Compressed 371409248 bytes into 172025694 bytes ==> 46.32%) 
- .\lizard-MyBuild.exe -49f .\system_other.img .\system_other.img.liz.49 (Compressed 371409248 bytes into 168488030 bytes ==> 45.36%)

Compression ratio of **lizard.exe**:
- lizard -25f .\system_other.img .\system_other.img.liz.25 (Compressed 371409248 bytes into 182706984 bytes ==> 49.19%)
- lizard -29f .\system_other.img .\system_other.img.liz.29 (Compressed 371409248 bytes into 178186870 bytes ==> 47.98%)
- lizard -45f .\system_other.img .\system_other.img.liz.45 (Compressed 371409248 bytes into 167356722 bytes ==> 45.06%)
- lizard -49f .\system_other.img .\system_other.img.liz.49 (Compressed 371409248 bytes into 165760838 bytes ==> 44.63%)

**Comment by inikep** [comment]
This is probably related to searching matches in a hash table. 
1. 32-bit compilation can give slightly lower ratio than 64-bit.
2. Please try compilation with defined `LIZARD_RESET_MEM`. It will clear a hash table at start of compression. This step is normally skipped to make compression faster.

**Comment by yunhua-deng** [comment]
> 1. 32-bit compilation can give slightly lower ratio than 64-bit.

Yep, my 64-bit complication slightly beats 32-bit one regarding the ratio.

> 2. Please try compilation with defined LIZARD_RESET_MEM. It will clear a hash table at start of compression. This step is normally skipped to make compression faster.

I added #define LIZARD_RESET_MEM TRUE to lizard_compress.c, but no luck, made no difference in my case.

Wondering how did you make the complication using Visual Studio, what are the configurations?

**Comment by inikep** [comment]
Projects for VS are included in this repo. More information at https://github.com/inikep/lizard/tree/lizard/visual
