### ISSUE TITLE
calling LZ5_compress_default causes crash

### ISSUE THREAD

**Issue by GregSlazinski** [inikep/lz5#4]
Default stack size on Windows is 1 MB
and size of LZ5_stream_t exceeds that limit
I had to change:
# define HEAPMODE 0

to
# define HEAPMODE 1

in order to prevent crashes.

I suggest this should be set to 1 by default

**Comment by inikep** [comment]
Thanks for reporting. It's fixed here:
https://github.com/inikep/lz5/commit/229b6b70266c15ef061b0a031a79dab91585fac7
